---
name: Deploy Portfolio app

on:
    workflow_run:
        workflows: ['Basic Docker Build']
        types:
            - completed

jobs:
    deploy-react-to-gh-pages:
        name: Deploy React app to gh pages
        runs-on: ubuntu-latest

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v4

            # setup nodejs environment
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: '16.20.2'

            # Change homepage property in package.json
            - name: Update homepage in package.json
              run: |
                  # Use jq to replace the homepage property
                  jq '.homepage = "https://${{ github.actor }}.github.io/Portfolio"' package.json > temp.json && mv temp.json package.json

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-

              # install dependencies
            - name: Install dependencies
              run: npm i

            # build the react app
            - name: Build
              run: npm run build

            # deploy the react app to github pages
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build # directory to deploy
